### ISSUE TITLE
update `_pkgdown.yml` theme to pulse - success and breeze-light for code

### ISSUE THREAD

**Issue by ernestguevarra** [rapidsurveys/squeacr#85]
section on template would look like this:

```YAML
template:
  bootstrap: 5
  bootswatch: pulse
  theme: breeze-light
  ganalytics:
  bslib:
    pkgdown-nav-height: 100px
```
